const mockData: profile = {
    username: 'Morty Smith',
    rating: 4.8,
    description:
        'Lorem ipsum dolor sit amet consectetur adipiscing elit pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas integer eget aliquet nibh praesent tristique magna sit amet purus gravida quis blandit turpis cursus in hac habitasse platea dictumst quisque sagittis purus sit amet volutpat consequat mauris nunc congue',
    tel: '0XX-XXX-XXXX',
};
const jobData = [
    {
        taskId: 1,
        title: 'Task 1',
        startDate: '2024-03-10',
        endDate: '2024-03-15',
        location: 'Location 1',
        workers: 5,
        category: 'Category 1',
        wages: 100,
    },
    {
        taskId: 2,
        title: 'Task 2',
        startDate: '2024-03-12',
        endDate: '2024-03-17',
        location: 'Location 2',
        workers: 3,
        category: 'Category 2',
        wages: 150,
    },
    {
        taskId: 3,
        title: 'Task 3',
        startDate: '2024-03-14',
        endDate: '2024-03-19',
        location: 'Location 3',
        workers: 7,
        category: 'Category 3',
        wages: 200,
    },
    {
        taskId: 4,
        title: 'Task 4',
        startDate: '2024-03-16',
        endDate: '2024-03-21',
        location: 'Location 4',
        workers: 2,
        category: 'Category 1',
        wages: 120,
    },
    {
        taskId: 5,
        title: 'Task 5',
        startDate: '2024-03-18',
        endDate: '2024-03-23',
        location: 'Location 5',
        workers: 6,
        category: 'Category 2',
        wages: 180,
    },
];
const pastData = [
    {
        taskId: 1,
        title: 'Task 1',
        startDate: '2024-03-10',
        endDate: '2024-03-15',
        location: 'Location 1',
        workers: 5,
        category: 'Category 1',
        wages: 100,
    },
    {
        taskId: 2,
        title: 'Task 2',
        startDate: '2024-03-12',
        endDate: '2024-03-17',
        location: 'Location 2',
        workers: 3,
        category: 'Category 2',
        wages: 150,
    },
    {
        taskId: 3,
        title: 'Task 3',
        startDate: '2024-03-14',
        endDate: '2024-03-19',
        location: 'Location 3',
        workers: 7,
        category: 'Category 3',
        wages: 200,
    },
    {
        taskId: 4,
        title: 'Task 4',
        startDate: '2024-03-16',
        endDate: '2024-03-21',
        location: 'Location 4',
        workers: 2,
        category: 'Category 1',
        wages: 120,
    },
    {
        taskId: 5,
        title: 'Task 5',
        startDate: '2024-03-18',
        endDate: '2024-03-23',
        location: 'Location 5',
        workers: 6,
        category: 'Category 2',
        wages: 180,
    },
    {
        taskId: 6,
        title: 'Task 6',
        startDate: '2024-03-20',
        endDate: '2024-03-25',
        location: 'Location 6',
        workers: 4,
        category: 'Category 3',
        wages: 220,
    },
    {
        taskId: 7,
        title: 'Task 7',
        startDate: '2024-03-22',
        endDate: '2024-03-27',
        location: 'Location 7',
        workers: 3,
        category: 'Category 1',
        wages: 130,
    },
    {
        taskId: 8,
        title: 'Task 8',
        startDate: '2024-03-24',
        endDate: '2024-03-29',
        location: 'Location 8',
        workers: 5,
        category: 'Category 2',
        wages: 160,
    },
];
