name: Next.js CD All

on:
  push:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            
            cd /home/${{ secrets.USERNAME }}/frontend/${{ github.ref_name }}/
            
            git pull origin ${{ github.ref_name }}
            
            cd my-app/
            
            npm install
            
            pm2 describe frontend >> /dev/null && (pm2 stop frontend; pm2 delete frontend)
            
            if [ "${{ github.ref_name }}" = "main" ]; then
              npm run build && pm2 start npm --name "frontend" -- run start
            elif [ "${{ github.ref_name }}" = "develop" ]; then
              pm2 start npm --name "frontend" -- run dev
            fi

            pm2 save
